-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 15:26:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EQUIPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EQUIPE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPE` (
  `idEQUIPE` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomEquipe` VARCHAR(45) NULL,
  PRIMARY KEY (`idEQUIPE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYE` (
  `nummatricule` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `EQUIPE_idEquipe` INT NOT NULL,
  `EQUIPE_idEQUIPE` INT UNSIGNED NOT NULL,
  `EMPLOYE_nummatricule` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`nummatricule`),
  INDEX `fk_EMPLOYE_EQUIPE_idx` (`EQUIPE_idEQUIPE` ASC) VISIBLE,
  INDEX `fk_EMPLOYE_EMPLOYE1_idx` (`EMPLOYE_nummatricule` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYE_EQUIPE`
    FOREIGN KEY (`EQUIPE_idEQUIPE`)
    REFERENCES `mydb`.`EQUIPE` (`idEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYE_EMPLOYE1`
    FOREIGN KEY (`EMPLOYE_nummatricule`)
    REFERENCES `mydb`.`EMPLOYE` (`nummatricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUALIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QUALIFICATION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QUALIFICATION` (
  `id_Qualification` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Qualification`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYE_has_QUALIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYE_has_QUALIFICATION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYE_has_QUALIFICATION` (
  `EMPLOYE_nummatricule` INT UNSIGNED NOT NULL,
  `QUALIFICATION_id_Qualification` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`EMPLOYE_nummatricule`, `QUALIFICATION_id_Qualification`),
  INDEX `fk_EMPLOYE_has_QUALIFICATION_QUALIFICATION1_idx` (`QUALIFICATION_id_Qualification` ASC) VISIBLE,
  INDEX `fk_EMPLOYE_has_QUALIFICATION_EMPLOYE1_idx` (`EMPLOYE_nummatricule` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYE_has_QUALIFICATION_EMPLOYE1`
    FOREIGN KEY (`EMPLOYE_nummatricule`)
    REFERENCES `mydb`.`EMPLOYE` (`nummatricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYE_has_QUALIFICATION_QUALIFICATION1`
    FOREIGN KEY (`QUALIFICATION_id_Qualification`)
    REFERENCES `mydb`.`QUALIFICATION` (`id_Qualification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
